version: '2'
services:
    first:
        build: first
        ports:
            - "3000:8080"
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_PTRACE

    second:
        build: second
        ports:
            - "5001:8080"
        security_opt:
            - seccomp:unconfined

    third:
        build: third
        ports:
            - "3131:8080"
