version: '2'
services:
    first:
        build: first
        ports:
            - "3000:3000"
    second:
        build: second
        ports:
            - "5001:5001"
        security_opt:
            - seccomp:unconfined

    third:
        build: third
        ports:
            - "3131:3131"
